# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Dan Wells GitHub pages"
baseurl: "/portfolio-jekyll"
# url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
