# Site settings
title: Daniel Wells
email: danielwells.usnret@gmail.com
username: danwells 
twittername: dwellsusnret
description: "Dan Wells GitHub pages"
baseurl: "/portfolio-jekyll"

# Build settings
markdown: kramdown
permalink: pretty
